### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Wr3tched** [bettercap/bettercap#100]
So are you. Why were you so rude the first time? Can I ask? Why such a prick about a fucking REQUEST? Personal issues? Fuck.

**Comment by evilsocket** [comment]
You've been banned by this repository and any other of this organization. There's a very specific issue template you refused to fill and, as mentioned in that very same template you probably didn't even read, the issue was closed right away. I didn't even know what commands or modules you enabled and you did not care to report, how am I supposed to tell you "when it's gonna stopp rickrolling"?

Kiddo, go play with your mom's dildos.
