### ISSUE TITLE
panis: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by PH-Vieira** [bettercap/bettercap#1049]
runtime error when running 'sudo bettercap'

### Environment: Linux kali 6.3.0-kali1-amd64

bettercap v2.32.0 (built for linux amd64 with go1.21.0)
Kali linux 2023.3
go version go1.18 gccgo (Debian 13.2.0-2) 13.2.0 linux/amd64
just 'sudo bettercap'

sudo bettercap -debug
bettercap v2.32.0 (built for linux amd64 with go1.21.0) [type 'help' for a list of commands]

Stopping modules and cleaning session state ...
panic: runtime error: index out of range [0] with length 0
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd4d846]

goroutine 1 [running]:
github.com/bettercap/bettercap/session.(*Session).Close(0xc0001c0a80)
        /build/bettercap-StA1LY/bettercap-2.32.0+git20230725/session/session.go:190 +0x126
panic({0x1190380?, 0xc0000e6000?})
        /usr/lib/go-1.21/src/runtime/panic.go:914 +0x21f
github.com/bettercap/bettercap/routing.update()
        /build/bettercap-StA1LY/bettercap-2.32.0+git20230725/routing/update_linux.go:40 +0x606
github.com/bettercap/bettercap/routing.Update()
        /build/bettercap-StA1LY/bettercap-2.32.0+git20230725/routing/tables.go:19 +0x71
github.com/bettercap/bettercap/routing.Gateway({0x11f732c, 0x4}, {0xc00012b5e8, 0x5})
        /build/bettercap-StA1LY/bettercap-2.32.0+git20230725/routing/tables.go:23 +0x5a
github.com/bettercap/bettercap/network.FindGateway(0xc000281300)
        /build/bettercap-StA1LY/bettercap-2.32.0+git20230725/network/net_gateway.go:10 +0x36
github.com/bettercap/bettercap/session.(*Session).Start(0xc0001c0a80)
        /build/bettercap-StA1LY/bettercap-2.32.0+git20230725/session/session.go:254 +0x2b4
main.main()
        /build/bettercap-StA1LY/bettercap-2.32.0+git20230725/main.go:49 +0x43f

### Steps to Reproduce

1. install bettercap as usual, install go and libcap-dev
2. run sudo bettercap

Expected behavior: work normally

Actual behavior: runtime error, panic

**Comment by VhaTer** [comment]
Exact same error 
6.1.0-kali9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux

**Comment by BSYBITAH** [comment]
the same for me! I try many solutions but it doesn't still working! Need help here pls

**Comment by 404useryv35notfound** [comment]
same here, did anyone find a solution? 6.5.0-kali2-arm64

**Comment by meditant** [comment]
To install the latest version of Bettercap, use the command:

go install github.com/bettercap/bettercap@latest
After installation, Bettercap works, but sudo might not find it. This issue occurs because sudo does not automatically recognize commands in the user's path.

There are two ways to resolve this:

1. Use the Full Path
Directly specify the full path to the Bettercap executable when using sudo. The default path is usually /home/user/go/bin/bettercap. So, the command should be:  sudo /home/user/go/bin/bettercap

2. Add to sudo's Secure Path
Alternatively, you can add your user's path to sudo's secure path:

Open the sudoers file with the command sudo visudo.
Look for a line that begins with Defaults secure_path= and add your user's path to it. For example:

Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user/go/bin"

Save and exit the editor.

After this modification, you should be able to run Bettercap with sudo without specifying the full path:

sudo bettercap

This will make Bettercap accessible to sudo, allowing it to be executed easily.

Best

**Comment by iagor1** [comment]
Tested in kali 6.5.0 x86 and worked just fine thx

**Comment by AnassZn** [comment]
![Capture d’écran du 2024-04-28 10-31-54](https://github.com/bettercap/bettercap/assets/166523825/81a898b1-ddfb-4637-937c-1c13d6437cd6)
 la meme probleme et sans solution

**Comment by evilsocket** [comment]
fixed here https://github.com/bettercap/bettercap/releases/tag/v2.33.0
