### ISSUE TITLE
Cryptominer caplet still being loaded when trying to use web UI.

### ISSUE THREAD

**Issue by maxlee-diagnoseearly** [bettercap/bettercap#1068]
caplets don't load themselves, if you experienced this miner being loaded is because one way or another you enabled it.

_Originally posted by @evilsocket in https://github.com/bettercap/bettercap/issues/729#issuecomment-653526721_

**Comment by maxlee-diagnoseearly** [comment]
Hi there!

This is still ongoing. I didn't go out of my way to activate a cryptominer (which shouldn't be hanging out in this software to begin with).

Could we get this cleaned up?

**Comment by evilsocket** [comment]
it is one of the caplets, its point is exactly to inject a crypto-miner via MITM on webpages, and the javascript file gets detected by AVs. Not sure what the big deal is since that as i said, you are in control of caplets so you won't be infected by a miner.

https://github.com/bettercap/caplets/tree/master/crypto-miner

**Comment by maxlee-diagnoseearly** [comment]
Ah, my ignorance. Forgive me.

Cheers!
