### ISSUE TITLE
https.proxy causes some connections to be dropped (cannot handshake client eof error)

### ISSUE THREAD

**Issue by maxiedaniels** [bettercap/bettercap#113]
### Prerequisites

* [x ] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [ x] I am running the [latest stable version](https://github.com/bettercap/bettercap/releases).
* [ x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.
* [ x] I understand I don't necessarily have to paste this `Prerequisites` section in the issue.

### Description

*Description of the bug or feature request*

### Environment

Please provide:

* OS version and architecture you are using.
Kali Rolling 2017.2
* Go version if building from sources.
1.10
* Command line arguments you are using.
bettercap (as root)

* Caplet code you are using (if any).
http-req-dump.js on http and https proxy

* Interactive session commands you are using (if any).
arp.spoof.targets x.x.x.x
set http.proxy.script http-req-dump.js
set https.proxy.script http-req-dump.js
arp.spoof on

** Errors I'm seeing **
I'm showing a few errors:

A) I'm seeing [war] Client does not support SNI. The client I'm testing against is my iPhone, not sure if that makes a difference.

B) Many websites or components of websites are showing 'WARN: Cannot handshake client [somewebaddress] EOF

C) **Edit** Forgot to write this error down: Cannot handshake client [somewebaddress] tls: client using inappropriate protocol fallback

This results in a page not loading at all, or parts of pages not loading.

**Comment by alexmozzhakov** [comment]
... and another one
`WARN: Cannot handshake client i.instagram.com remote error: tls: unknown certificate authority`

**Comment by evilsocket** [comment]
@alexmozzhakov nothing, that warning simply means the Instagram app refused to connect because you're MITM-ing with a certificate signed by bettercap :) You'd have the same exact problem with the previous version (unless you install the custom CA on the device), maybe different warning messages but that only means the client is properly enforcing TLS checks

**Comment by alexmozzhakov** [comment]
yeah, but the `-X` option wasn't so aggressive

**Comment by evilsocket** [comment]
Of course not, the `-X` option only enabled the sniffer (the equivalent of `net.sniff` now), while this implies the use of `arp.spoof` ( -S ARP or just default ) plus `https.proxy` ( `--https-proxy` ).

**Comment by alexmozzhakov** [comment]
@evilsocket oh, thank you very much

**Comment by evilsocket** [comment]
@maxiedaniels this is expected behavior. In order for bettercap's `https.proxy` module to modify/view any of the contents inside the SSL/TLS session, it needs to terminate it. So instead of `browser <-> google`, it becomes `browser <-> bettercap <-> google`. When it terminates it, it needs to send your browser a certificate signed by a CA your browser trusts essentially pretending to be Google. You can insert your own CA to have bettercap sign certificates using your CA but you'll also [have to import that CA into each of your browsers](https://www.bettercap.org/legacy/index.html#https).

**Comment by maxiedaniels** [comment]
@evilsocket Interesting - thank you for the response. I assumed an invalid certificate error would show up, but I didn't think connections would be killed. Aside from loading up fake certs on a target system, there is no other way to avoid the issue right?

**Comment by evilsocket** [comment]
Well that depends on a few factors, like type of browser, version, os, if the HSTS was already cached, SSL version in the original certificate, etc etc so messages might vary :D Right, intercepting TLS connections is not possible if proper certificate pinning is performed unless you install the CA on the device ... luckily I'd add otherwise the whole internet would be broken :D
