### ISSUE TITLE
Docker wifi.* not working

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#127]
Running `wifi.recon on` with the latest build (after closing #123) returns 
` [err] Interface not in monitor mode? Cannot set rfmon for this handle`
even after putting to monitor mode manually. 
IMHO, I don't think docker support should be implemented for this particular type of software at all.
There are a lot of other critical and much important and useful features to be implemented.

**Comment by evilsocket** [comment]
That message means that libpcap can't set the interface in monitor mode or interact with it properly, not a bug but simply hardware support. I agree Docker support is not top priority but it's easy to have basic supporto so why not.

**Comment by alexmozzhakov** [comment]
@evilsocket well, it works without docker, so I'm not sure about hardware issue status.

**Comment by evilsocket** [comment]
with that status i just mean some incompatibility between the software/drivers/hardware/os, it's generic :)

**Comment by xmijo** [comment]
I too kept getting the same error despite manually setting monitor mode. After some head-scratching it dawned on me it was because bettercap had automatically bound itself to my eth0 interface and not wlan. And it seems `wifi.recon` attempts to interact with the interface that bettercap is currently bound to. If this is the case then it is no wonder it failed to set monitor mode for eth0. A hardware issue indeed :D

The issue was solved by simply starting bettercap with the -iface flag and binding it to my wlan interface instead.

It felt like a facepalm at the time but I can definitely see situations in which it is easy to make the same mistake (@alexmozzhakov?). It's not obvious which interface `wifi.recon` is interacting with. The function name itself implies that it should at least be interacting with a wlan interface.

A suggestion would be to include the interface name in the error message to make it more clear what it was trying to interact with. Or alternatively, to offer some flexibility which interface to `wifi.recon` with (might also be useful if there's several wlan interfaces present for ability to switch between them?). Perhaps even go so far as to add functionality for switching the bettercap bound interface on the fly in interactive mode?

**Comment by evilsocket** [comment]
> It's not obvious which interface wifi.* is interacting with.

Is it not obvious that a module named `wifi.*` needs to be used with a wifi card? Really?

**Comment by xmijo** [comment]
I think it's easy to make this mistake because one might assume a wlan interface would be used, even if bettercap happens to currently be bound to e.g. eth0. And how about the case of several wifi cards present?

**Comment by evilsocket** [comment]
That is exactly why there's the `-iface` parameter ...

**Comment by evilsocket** [comment]
Also you can see anytime what interface you're using with `get iface.*`.
