### ISSUE TITLE
Arp spoof target bug

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#136]
arp.spoof module seems so somehow save previous targets after running `arp.spoof off`, so when I restart it for a second target, it shows 
After `arp.spoof off`:
`Restoring ARP cache of 1 targets`
My `get arp*`:
` arp.spoof.targets: 'XX:XX:XX:XX:XX:XX'`
Then on `arp.spoof on`:
`ARP spoofer started, probing 2 targets.`

**Comment by evs-pn** [comment]
why ignore / delete the issue template ?! pls try to use in oder to get useful answers from the dev team.

**Comment by wcrigger** [comment]
there's a form for that dude, use it.  Also there is a JSON environment file in ~, added as a feature request not long ago that stores your environment variable persistent through executions of bettercap.  I myself noticed it'd be nice for an optional environment clear. Otherwise I'm editing JSON by hand.

**Comment by evilsocket** [comment]
@alexmozzhakov could you please stop opening issues without filling the details and without understanding the difference between a bug and intended behaviour? Thanks.
