### ISSUE TITLE
support for openwrt CC ar71xx

### ISSUE THREAD

**Issue by cyrus104** [bettercap/bettercap#207]
# Prerequisites

Run several searches and looked through the open and closed issues. 
---

Support check and maybe feature request. 

### Environment

Please provide:
Latest bettercap, self compiled and precompiled
Kali Linux on amd64
Openwrt with CC

**Expected behavior:**
I would like to be able to run bettercap on openwrt. I've tested the mips prebuilt on openwrt CC ar71xx version. The file will not run, not recognized in ash or bash. 

I have compiled a version from the git and also tested it with the same results. 

I might be missing something, like bettercap will never be able to work on busybox but I could not find that. 

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment]
@cyrus104 ping?

**Comment by cyrus104** [comment]
Haven't had a chance to get that info out yet. Will get it to you in a few
hours, thank you for being patient.

**Comment by evilsocket** [comment]
Mmmm I'm not super familiar with openwrt, but usually you get that error when the architecture is compatible, but the system linker is different, which means it should be compiled with an OpenWRT toolchain instead ... can you install Go on it? :D

**Comment by cyrus104** [comment]
I don't see it in the opkg for openwrt,  I did find the link below that is a little dated.

https://github.com/GeertJohan/openwrt-go

This seems to need a kernel patch and recompile. I would need to cross compile that because of the limited space.

To double check I'm following, you are checking if I can install go to compile it natively? I think space will be the end issue.

**Comment by evilsocket** [comment]
I guess whoever is interested in this build, will either need to find a way to install an updated Go on the system itself, or a way to [cross compile it using some OpenWRT toolchain](https://github.com/bettercap/bettercap/wiki/Cross-Compilation-(-ARM-example-)).

**Comment by cyrus104** [comment]
I'll give the cross compiling a shot, my board doesn't have enough storage
on it without mounting an external drive.

Is going to take a few days for me to get the time, will try through the
weekend.

**Comment by evilsocket** [comment]
thanks so much for helping, meanwhile i'll try as well and update you here in case i have good (or bad) news ^_^

**Comment by nivong** [comment]
The pineapple tetra is no where strong enough to run more than 2 or 3 clients. I think.

**Comment by nivong** [comment]
why remove my comment...?

**Comment by evilsocket** [comment]
@nivong because your opinion on how many "clients" (whatever clients you were referring to) a Tetra can handle is pointless for this issue, we're discussing how to crosscompile.

**Comment by nivong** [comment]
please explain that the next time instead of deleting ;) anyway what I was saying seeing that this is going to be running on a pineapple tetra that that is not powerful enough to run bettercap and the modules.

You are better off using the pineapple to capture the traffic and forward that to a laptop

**Comment by evilsocket** [comment]
@nivong if you're offtopic i don't have to explain anything before moderating the issue, stop doing that.

**Comment by xmijo** [comment]
Confirming the executable for ARM7 not working on an OpenWRT router running Linux 4.4.92 armv7l. Same error as above. Insufficient space for installing Go on this thing, unfortunately, else I'd try to compile it on the device.

**Comment by xmijo** [comment]
After investigating this, I'm led to believe the binary must be built with musl library (instead of glibc).

I found a tutorial [here](https://medium.com/def-repr-self/cross-compiling-go-and-cgo-targeting-armv7l-musl-libc-f96c610834a8) on how to do this but I'm just too much of a Go noob to test this myself. Perhaps someone with more experience could give this a shot?

Please note I'm not sure if this will work or not.

**Comment by xmijo** [comment]
So I compiled it on OpenWRT and it runs. But it looks like this:

![image](https://user-images.githubusercontent.com/24359963/43779063-a8eb92de-9a57-11e8-8675-ed0af284de6b.png)

This is probably caused by my encrypted DNS requests. Haven't had time to test it without encrypted dns yet, or to test any other Bettercap functionalities. I'm in need of a break after going down this rabbit hole that took me to hell and back but the resulting process is fairly simple, the issues were mostly related to the compilation of libpthread. Anyway, Bettercap basically needs to be compiled with musl, which is what OpenWRT packages use.

The binary weighs in at a whopping 19MB, which could be a big issue for OpenWRT devices that often don't have the flash space to spare. It might be possible to reduce the size by compiling libpthread with flags disabling unneeded functionality? Or maybe UPX can help with that, I'll give that a try later too.

**Comment by ThatGuyJoe** [comment]
Just wanted to inquire what progress you guys have now. 

I'll try to experiment with this on a mvebu cortexa9 (Linksys WRT 1900AC v1)

uname:
```
Linux OpenWrt 4.14.131 #0 SMP Thu Jun 27
12:18:52 2019 armv7l GNU/Linux
```

/proc/cpuinfo:
```
processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 25.00
Features        : half thumb fastmult vfp edsp vfpv3 tls idiva idivt vfpd32 lpae                                                                                                                                                             
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2

processor       : 1
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 25.00
Features        : half thumb fastmult vfp edsp vfpv3 tls idiva idivt vfpd32 lpae                                                                                                                                                             
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2

Hardware        : Marvell Armada 370/XP (Device Tree)
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by tapper82** [comment]
Hi if you do get this building for OpenWrt pleas make it run on an up to date build. OpenWrt 18.06.4 or even better test it out on the soon to be stable 19.07. You can find snapshots here: 
https://downloads.openwrt.org/releases/19.07-SNAPSHOT/
Thanks. I am not a OpenWrt dev just a fan.

**Comment by cyrus104** [comment]
I'm going to go ahead and close this as somebody has just recently published a working makefile for building for this chipset.

https://github.com/hak5/pineapple-packages-community/blob/master/network/bettercap/Makefile
