### ISSUE TITLE
Enable adding custom cmds in caplets such as ^D

### ISSUE THREAD

**Issue by SkypLabs** [bettercap/bettercap#217]
### Environment

Latest stable version on Kali 2018

### Feature request description

It would be nice ~~to add `exit` as an alias of the `quit` command~~ to be able to use `CTRL+D` to stop and quit bettercap. However, I'm wondering if it wouldn't be a design choice not to accidentally close bettercap.

-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by alexmozzhakov** [comment]
@SkypLabs 
Given this https://github.com/bettercap/bettercap/blob/39ed078204c37fbde454b9e3ac88fe111acb70e4/session/session.go#L229-L234
I think you can submit a PR for the issue yourself.

**Comment by yungtravla** [comment]
I think it's best if we enable escaping of characters in (quoted) variables, and also enable a `define <name> <eval>` so that we can do this from a caplet. (ie. `define "\D" "exit"`)

Because if you were to set a lot of configurations from within the interactive session, and then use hotkeys like CTRL+E, CTRL+X or CTRL+W, it would be annoying if you accidentally hit CTRL+D and end the session.

Escaping could also enable the reuse of variables in caplets, for example `define module.reset "http.proxy off; include $capletPath; http.proxy on"`.

**Comment by yungtravla** [comment]
Most of bettercap's core logic has already been implemented, very soon it will be entirely up to the individual what they can do with it :1st_place_medal:

**Comment by evilsocket** [comment]
I don't like the design idea to allow custom commands like that, but I'll switch ^C to ^D given ^C was not decided for a particular reason.

**Comment by alexmozzhakov** [comment]
@evilsocket actually, just thought about it. You can use caplets for the purpose of aliasing
