### ISSUE TITLE
arp.spoof onpanic: runtime error

### ISSUE THREAD

**Issue by dootyfree** [bettercap/bettercap#333]
Getting error below, and using stable release

arp.spoof onpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcdc2d9]

goroutine 99 [running]:
github.com/bettercap/bettercap/modules.(*HTTPProxy).Start.func1(0xc421386e60)
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/modules/http_proxy_base.go:328 +0x189
created by github.com/bettercap/bettercap/modules.(*HTTPProxy).Start
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/modules/http_proxy_base.go:320 +0x3f
*

### Environment

Please provide:

*2.8.0
Linux kali 4.12.0-kali2-amd64 #1 SMP Debian 4.12.12-2kali1 (2017-09-13) x86_64 GNU/Linux
no args
{set http.proxy.sslstrip true
set https.proxy.script caplets/http-req-dump.js
set http.proxy.script caplets/http-req-dump.js
http.proxy on}

arp.spoof onpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcdc2d9]

goroutine 99 [running]:
github.com/bettercap/bettercap/modules.(*HTTPProxy).Start.func1(0xc421386e60)
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/modules/http_proxy_base.go:328 +0x189
created by github.com/bettercap/bettercap/modules.(*HTTPProxy).Start
	/home/evilsocket/gocode/src/github.com/bettercap/bettercap/modules/http_proxy_base.go:320 +0x3f

### Steps to Reproduce

1. set http.proxy.sslstrip true
2. set https.proxy.script caplets/http-req-dump.js
3. set http.proxy.script caplets/http-req-dump.js
4. http.proxy on
5. error

**Expected behavior: not error

**Actual behavior:  error

**Comment by eenblam** [comment]
@dootyfree I haven't managed to reproduce on OS X or an Ubuntu image, but I can try it on Kali a bit later. Did you do anything else, e.g. add other settings?

That line should only panic if the HTTPProxy's Server is nil, which should never happen if `HTTPProxy.Configure(...)` doesn't fail. The call chain from startup looks something like this:

- Module is registered in `main.go`, which calls `NewHttpProxy(sess)` and `NewHttpsProxy(sess)`. I'm ignoring the latter from here, since you didn't seem to turn it on.
    - `NewHttpProxy(sess)` creates an `HttpProxy` (a session module) with an `HTTPProxy` attribute. It also registers handlers for related commands, e.g. `"http.proxy on"`.
    - It also registers callbacks against the `Session.Environment` for whenever you do things like `set VAR VAL`. So, your initial sets have some impact.
- `sess.Run("http.proxy on")` calls `HttpProxy.Start()` via `HttpProxy.Handlers[i].Exec(...)`. `Start()` does two things:
    - `HttpProxy.Configure()`, which *gets the variables you set* and passes them into `HttpProxy.HTTPProxy.Configure()`
    - `HttpProxy.HTTPProxy.Start()`, which seems to panic for you due to the server being nil.

There are a few ways for this to fail for a regular `HTTPProxy`.
- Bettercap either couldn't read or couldn't process (it runs the JS through the Otto interpreter) the file set to `http.proxy.script`.
- Similar for `http.proxy.injectjs` - if you pass a filename that Bettercap finds via `core.Exists(filename)`, then it will try to load it. If the file exists but can't be read for some reason, `Configure()` returns an error.

However, both of these failures get caught on my machine when the caplet is unavailable or if I break the JS in the caplet. Otherwise, `HTTPProxy.Configure()` won't return prior to initializing `HTTPProxy.Server`.

Again, I'll set aside some time to try this on Kali later. In the meantime, can you:
- Confirm that you aren't setting anything else funny
- Run `sudo bettercap -debug` and provide any additional logs you might be seeing from Bettercap
- Confirm that you have github.com/bettercap/caplets installed in the directory you're running Bettercap from
- Confirm whether or not this still breaks if you skip step 2. That step shouldn't impact step 4 unless there's something especially weird happening, as `HttpProxy` and `HttpsProxy` each manage a separate `HTTPProxy`, have their own handlers, have their own environment variables, etc.
