### ISSUE TITLE
Wifi.deauth skip BSSID 

### ISSUE THREAD

**Issue by khanhson2979** [bettercap/bettercap#375]
wifi.deauth BSSID : Start a 802.11 deauth attack, if an access point BSSID is provided, every client will be deauthenticated, otherwise only the selected client. Use a broadcast BSSID (ff:ff:ff:ff:ff:ff) to iterate every access point with at least one client and start a deauth attack for each one. 
can I skip some BSSID ?? 
Regards

**Comment by yungtravla** [comment]
Are you suggesting a blacklist feature that will target all BSSIDs except from the blacklisted ones?

Otherwise you can target all endpoints except for the ones you want to skip.

**Comment by leonardoporp** [comment]
I think you could also give the possibility to deauth everyone without the once that I write, cause if there is a big network with hundreds pc i cannot write all of them, but I can write just my devices that are the once I don't want to deauth

**Comment by yungtravla** [comment]
You can enter the MAC of an access point as deauth target which will disassociate all clients from that AP, unless that AP encrypts management frames (802.11w networks), which makes deauthing/disassociating ineffective.

**Comment by leonardoporp** [comment]
Is what I wanted too
👊❤️🤙

-------- Original Message --------

**Comment by yungtravla** [comment]
A `wifi.deauth.skip` variable would only be of use with an additional `set wifi.deauth.all true`, otherwise we still have to manually set each target.

**Comment by its0x08** [comment]
and also a way do skip the wifi state would be great!!
like skipping open wifis or wep ones in order to work only with the wpa/wpa2 or wps only.. something like that !
its so boring to do all that selection every time u run bettercap
because why would i go deauth  or assoc all the open wifis when i just need a wpa/wpa2 to work with!!!
and also without this option the wifi.deauth * and wifi.assoc * makes too much noise around If ur in a time sensitive red teaming !
