### ISSUE TITLE
Feature request --force-colors arg

### ISSUE THREAD

**Issue by SuperOP535** [bettercap/bettercap#396]
This is not a report but a suggestion, could you please add a --force-colors arg for terminals that do support colors (e.g. Termux) but bettercap doesn't detect it correctly?

**Comment by SuperOP535** [comment]
@evilsocket why was this closed? may I have an explanation please.

**Comment by yungtravla** [comment]
Colors are enabled by default. If you are using a dumb terminal that does not know how to display them, you can disable them with `--no-colors`.

**Comment by SuperOP535** [comment]
@yungtravla My terminal supports colors but bettercap does not detect that it does so, my problem is that I want to _force enable_ colors since they get disabled because of this.

**Comment by yungtravla** [comment]
@SuperOP535 what terminal are you using?

**Comment by evilsocket** [comment]
@SuperOP535 my point is simple: instead of forcing colors when bettercap behaves in a weird way (misdetecting colors compatibility), we should fix the misdetection in the first place! if you could open another issue filling the template and describing your problem with the colors support, we'll be glad to help! :D

**Comment by yungtravla** [comment]
@SuperOP535 the issue is not bettercap, but your su environment.

When you run commands like `su` / `sudo` / `tsu`, your environment variable `TERM` will most likely be set to `dumb`.

You should be able to keep the termux environment variables, but even with `tsu -p -e` I cannot achieve this, so I manually set the TERM variable, like so:

```sh
tsu -p -c "TERM=X bettercap"
```

And colors will appear :)

![image](https://user-images.githubusercontent.com/29265684/54417803-e8c8b680-474e-11e9-8479-8a07d001758a.png)
