### ISSUE TITLE
Go compiling error on linux arm

### ISSUE THREAD

**Issue by ZimSec** [bettercap/bettercap#425]
When updating Bettercap on the raspberrypi go gives errors and Bettercap does not compile.

Version 2.13.1

go version go1.8.3 linux/arm
Linux raspberrypi 4.14.79-v7+ armv7l GNU/Linux

" # github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw
/root/go/src/github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw/raw_linux.go:317: undefined: unix.Errno
/root/go/src/github.com/bettercap/bettercap/vendor/github.com/mdlayher/raw/raw_linux.go:330: undefined: unix.Errno "

### Steps to Reproduce

1. sudo go get -u github.com/bettercap/bettercap

**Expected behavior:** 

Bettercap gets updated to the latest version.

**Actual behavior:**

Bettercap does not compile and gives the error displayed above.

**Comment by evilsocket** [comment]
can't reproduce, it builds flawlessly on my rpis

**Comment by ZimSec** [comment]
You can close this, it builds flawlessly on go version go1.11.5 linux/arm, but there is issues on that specific go lang version since I got the same issue on 2 different pi's with different os's with go1.8.3. Bit 1.11.5 give no issues

**Comment by RaduNico** [comment]
A very similar error occured to me un Xubuntu 18.04 while building:

vendor/github.com/mdlayher/raw/raw_linux.go:324: undefined: unix.Errno
vendor/github.com/mdlayher/raw/raw_linux.go:337: undefined: unix.Errno

The go version I used was 'go version go1.8 linux/amd64' downloaded from here: https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz

Upgraded to 'go version go1.12.2 linux/amd64' and the issue was gone. I posted this here because when I googled the issue this thread popped second, maybe it will be useful to some other folks. Cheers!
