### ISSUE TITLE
Can't install bettercap 2 on MacOS

### ISSUE THREAD

**Issue by Gwerb** [bettercap/bettercap#522]
This is not an issue in bettercap but in its installation, I tried installing the currently latest bettercap version (2.22 - Serge) for my OS (MacOS) and when i run the ./bettercap command i get this output:

dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: /Users/user/./bettercap
  Reason: image not found
Abort trap: 6

There aren't many tutorials or fixes out there so i have nothing else to do except post this issue

**Comment by evilsocket** [comment]
install libpcap and libusb from brew

**Comment by Drjacky** [comment]
@evilsocket They are installed.
> Warning: libpcap 1.10.4 is already installed and up-to-date.
To reinstall 1.10.4, run:
  brew reinstall libpcap
  
> Warning: libusb 1.0.26 is already installed and up-to-date.
To reinstall 1.0.26, run:
  brew reinstall libusb
  
My machine: macOS ventura 13.6, Apple Silicon
Bettercap version: v2.31.1 (as there is no precompiled binary for [2.32.0](https://github.com/bettercap/bettercap/issues/1053)

Error:
```bash
➜  bettercap_darwin_amd64_v2.31.1 ./bettercap
dyld[9843]: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: <977FD767-9488-35DA-A93F-0282CF4D135F> /Users/usernameeee/bettercap_darwin_amd64_v2.31.1/bettercap
  Reason: tried: '/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/lib/libusb-1.0.0.dylib' (no such file), '/usr/lib/libusb-1.0.0.dylib' (no such file, not in dyld cache)
[1]    9843 abort      ./bettercap
```

Maybe because in M1, the path is not in the `/usr/local/lib/`, and it's in `/opt/homebrew/lib`?!
