### ISSUE TITLE
apt-get install bettercap bettercap-caplets wrong location in https-ui.cap http-ui.cap 

### ISSUE THREAD

**Issue by N2Network** [bettercap/bettercap#530]
On the default install of Kali (Linux kali-pi 4.14.93-Re4son-v7+ #1 SMP Thu Jan 24 12:44:19 AEDT 2019 armv7l GNU/Linux)when apt-get install bettercap bettercap-caplets is used the http-ui.cap and https-ui.cap point to the wrong location for the web interface. They point to /usr/share/bettercap/ui when the files are in fact located in /usr/local/share/bettercap/ui I modified this line as follows:

 set https.server.path /usr/local/share/bettercap/ui
However, when I run the command
 bettercap -caplet http-ui
I'm able to see the web interface login. But when I click the login button nothing actually happens, tried on multiple browsers. I thought it might be an issue with permissions so I changed the http-ui.cap file back to default:
 set https.server.path /usr/share/bettercap/ui
and then just moved the folder:
 mv /usr/local/share/bettercap/ui /usr/share/bettercap
This however resulted in the same problem. The login button is broke on the web interface. What am I doing wrong here?

**Comment by N2Network** [comment]
Well I'm not sure why the apt-get install bettercap bettercap-caplets did not work as indicated above. However, I was able to circumvent this issue by compiling.

go get github.com/bettercap/bettercap
cd $GOPATH/src/github.com/bettercap/bettercap
make build 
sudo make install

**Comment by yungtravla** [comment]
Yes, it's recommended that you follow the install instructions in the docs https://www.bettercap.org/installation/

The http-ui command actually loads a caplet, because bettercap allows you to quickly execute caplets by typing the caplet name in the interactive session.

So basically your `http.server.path` configuration is ignored because it is also configured in the http-ui caplet, so you can change the `http.server.path` in the http-ui.cap file :)

**Comment by N2Network** [comment]
Thanks.

**Comment by mdubller** [comment]
i have everything setup as so. I am getting the same exact issue. the button doesnt work
