### ISSUE TITLE
Captive Portal capability?

### ISSUE THREAD

**Issue by mrbluecoat** [bettercap/bettercap#631]
Are there plans to include _Captive Portal_ capabilities in bettercap?  The only reference I could find with a brief search was @buffermet on https://github.com/bettercap/bettercap/issues/182

This is one of the few capabilities of MITMF that hasn't been ported to bettercap.

**Comment by buffermet** [comment]
Hey, I will push the caplet shortly :)

**Comment by mrbluecoat** [comment]
Thanks, @buffermet!  Ref?

**Comment by buffermet** [comment]
Hey, apologies for the delay. I've been quite busy but I will make time today to debug and package this.

**Comment by mrbluecoat** [comment]
P.S. @buffermet, you and @evilsocket are amazing!  I'm loving bettercap

**Comment by digitalirony** [comment]
any progress on this?

**Comment by buffermet** [comment]
I have a WIP captive portal packet proxy for Linux, and a DNS proxy module that is almost ready.

This will have limited capability unless using a packet proxy on Linux devices as it requires the nfqueue library to manage traffic down to the ethernet layer.

The DNS proxy module will only allow functionality up to a certain extent for MacOS and Windows users. It will redirect HTTP requests and DNS can block certain traffic until a user has successfully signed in via a captive portal, however this is easily bypassed with cached DNS replies as well as things like DoH (DNS over HTTPS).

So if you want a stable captive portal that allows no traffic/tunneling until a user successfully signed it, you will need Linux.

I'll aim to finish both modules next week.

**Comment by digitalirony** [comment]
Yeah, I deff plan to use linux.
This sounds pretty useful. wifiphisher is cool, but doesnt seem to do captive portal, just redirect for websites.
Fluxion and airgeddon are also nice, and have cool captive portals that work....however neither are very good at things like a "public wifi" captive portal.
Fluxion gives more control over using multiple interfaces, but doesnt allow for much customization for the actual portal side.
Airgeddon doesnt seem to be smart enough to use two interfaces, like one for deauth and one for ap.(since some of use dont have a good card that supports vif). 
I think bettercaps way of doing things already solves all the above issues, and has all the "features" of all of the above tools.

**Comment by digitalirony** [comment]
Also, I would be happy to help debug any issues. I am not an amazing coder, and deff not low level stuff. Buuuut, I am pretty good at sleuthing out bugs, and learning in the fly.
So if you need help testing just let me know.

**Comment by buffermet** [comment]
I will be working on the captive portal module from this fork until it's ready for PR: https://github.com/buffermet/scripts

The Linux version runs stable with create_ap and Android hotspots. The BSD/Unix version is WIP.

A few notes for review:

- timeout.js polyfill uses seconds instead of ms, no recursion supported, removeEventListener: error: bettercap becomes unresponsive
- env("os") not set by default yet (needs PR)
- unix/bsd version not tested yet (still needs DNS resolver ip rebind)
- allow combined usage of captiveportal.lease.delay and captiveportal.lease.resettime (might need resetpriority var)
- client download/upload usage not implemented yet (needs PR)
- ticker shell command output can't be muted (needs PR)

Example create_ap hotspot:

```sh
create_ap wlan0 wlan1 "Free WiFi" -g 10.0.0.1 --dhcp-dns 10.0.0.1 --no-dns
```

Thanks to the session script framework this has all come together very nicely. This module lets us easily create captive portal environments as a service or for spoofing, which enables all kinds of mass SMS/email harvesting/registration operations.

As always questions/feedback/ideas are welcome.
