### ISSUE TITLE
Bettercap wifi.recon on error.

### ISSUE THREAD

**Issue by LittleCHZY** [bettercap/bettercap#743]
So I've recently just gotten into the concept of kali but have gotten used to kali and gotten an easy understanding of how to use it in a short amount of time. So I've recently been looking into intercepting network handshakes and started off with using basic information online to find paths to take while doing this, and I soon came upon this error. I've been at this error for about an hour and have little to no leads.

Please, provide something to help.

### Environment

* bettercap v2.27.1.
* Kali Linux 2020.2.
* Wifi.recon on.
* Bettercap --iface wlan0mon.

### Steps to Reproduce

1. sudo airmon-ng check kill
2. sudo arimon-ng start wlan0mon (Because for some reason my wireless adapter doesn't work)
3. bettercap --iface wlan0mon
4. Wifi.recon on 

It should spit out info on networks around

[sys.log] [inf] [err] error while getting supported frequencies of wlan0mon exec: "iwlist": executable file not found in $PATH

--

**Comment by red0xff** [comment]
Just install the `wireless-tools` package, it comes with the iwlist command.
```
sudo apt update && sudo apt install -y wireless-tools
```

**Comment by LittleCHZY** [comment]
> Just install the `wireless-tools` package, it comes with the iwlist command.
> 
> ```
> sudo apt update && sudo apt install -y wireless-tools
> ```

Didn't help and  I've tried it before.

**Comment by q2dg** [comment]
The same here with Bettercap v2.28 and Fedora 32.

Wireless-tools are deprecated: iw command should be used instead.

The error is here: https://github.com/bettercap/bettercap/blob/2f3390cf363d3f2542e87359710b694ec3d386c8/network/net_linux.go#L86

**Comment by CyriusGentoo** [comment]
I ve the same problem whatever the process i use to obtain my wifi device in monitor mode : 
   - Use of airmon-ng => bettercap error
   - Use of ip and iw, => bettercap error
   - Use of bettercap only => bettercap error

The problem is not coming from wireless card or my Gentoo installation as it works with : 
    - Wireshark : i didn't check how it works
    - Aircrack-ng : use a bash script with iw calls (Airmon-ng)
    - wifite: check if airmon-ng exists in process

So i ve check the bettercap code : 

"/*
                         * Calling SetRFMon is fatal when the interface is already in monitor mode.
                         * gopacket has no GetRFMon analogue to SetRFMon with which we could check this, however ...
                         */
                        if !setRFMonMaybeFatal {
                                if err = ihandle.SetRFMon(true); err != nil {
                                        return fmt.Errorf("error while setting interface %s in monitor mode: %s", tui.Bold(ifName), err)
                                }
                        } else {
                                mod.Debug("SetRFMon on interface %s might be fatal, skipping this time", tui.Bold(ifName))
                        }"

And, indeed, as said in the comment, it s fatal in all cases for my case !!!

The problem is coming from the fact bettercap is implemented with the ethernet management tool : pcap.
As i read on web, this tool is old,partially wireless compatible and can't be used alone to implement it correctly.
It comes from TcpDump project...which, as i use it since long time ago, is amazing....

I then looked for a solution (for my personnal understanding) and found perhaps some information about to help you about : 
   1 - Kernel documentation on Wireless implementation : [https://wireless.wiki.kernel.org/](https://wireless.wiki.kernel.org/)
   2 -  a C sample on how to retrieve info on Wireless device : [https://alamot.github.io/nl80211/](https://alamot.github.io/nl80211/)
   3 - An explanation about Netlink, wifi and integration in Golang : [https://medium.com/@mdlayher/linux-netlink-and-go-part-1-netlink-4781aaeeaca8](https://medium.com/@mdlayher/linux-netlink-and-go-part-1-netlink-4781aaeeaca8) . You should really read the 3 parts of it.

Unfortunately, i can' t do more as i don't know golang. 
I understood netlink is done to discuss with userspace kernel drivers...only way (and used way by iw command) to retrieve the wireless mode.  
May i then suggest you to implement something simple : "if already in monitor mode : go, if not : error message explaining how to use ip, iw command or airmon-ng" thanks this golang wifi/netlink library ?

I hope it will help and i ll be able soon to test your tool.

**Comment by alien1777** [comment]
After trying "sudo arimon-ng start wlan0mon (Because for some reason my wireless adapter doesn't work)" command it keeps saying"zsh:unknown file attribute:B" 
Somone help
