### ISSUE TITLE
caplets don't load themselves, if you experienced this miner being loaded is because one way or another you enabled it.

### ISSUE THREAD

**Issue by guneysus** [bettercap/bettercap#753]
caplets don't load themselves, if you experienced this miner being loaded is because one way or another you enabled it.

_Originally posted by @evilsocket in https://github.com/bettercap/bettercap/issues/729#issuecomment-653526721_

I just followed the documention: https://www.bettercap.org/usage/

Please be responsible issues instead of blaming the user.

**Comment by evilsocket** [comment]
One of the caplets IS a miner, it's supposed to be injected in your target's webpage. Your AV just got triggered by the file, that doesn't mean it was running on YOUR computer. The CPU usage spike you experienced might be due to many reasons, bettercap can be very CPU intensive depending what modules are running.

Please understand how the software you are using works instead of blaming the developers because you don't.
