### ISSUE TITLE
how to see wifi ap's clients ? 

### ISSUE THREAD

**Issue by elig0n** [bettercap/bettercap#757]
How can I see a certain wifi AP's connected clients mac addresses (and other data if possible) through the CLI ?

**Comment by evilsocket** [comment]
wifi.recon BSSID
Set 802.11 base station address to filter for.

wifi.recon clear
Remove the 802.11 base station filter.

RTFM 

https://www.bettercap.org/modules/wifi/

**Comment by elig0n** [comment]
a. the docs only state that wifi.recon BSSID will filter a BSSID and not that it will also list clients.
b. why not have the option to list clients for any BSSID ? since they already appear scattered in the events list

**Comment by rolfen** [comment]
> wifi.recon BSSID Set 802.11 base station address to filter for.
> 
> wifi.recon clear Remove the 802.11 base station filter.
> 
> RTFM
> 
> https://www.bettercap.org/modules/wifi/

Your arrogant and useless answer only refers to **filtering** by base station. 

I am trying to figure out how to list clients for a particular base station and their MAC address.

`wifi.show` will produce a list of BSSIDs

```
6a:16:1b:64:b0:b4 clients:

┌─────────┬───────────────────┬────┬───────┬────────┬──────────┐
│ RSSI ▴  │       BSSID       │ Ch │ Sent  │ Recvd  │   Seen   │
├─────────┼───────────────────┼────┼───────┼────────┼──────────┤
│ -50 dBm │ c8:31:35:de:fa:3d │ 9  │ 78 kB │ 8.0 kB │ 22:22:47 │
│ -59 dBm │ 2e:21:02:13:a5:1a │ 9  │ 72 kB │ 103 kB │ 22:22:29 │
└─────────┴───────────────────┴────┴───────┴────────┴──────────┘
```

**Comment by evilsocket** [comment]
@rolfen My arrogant and useless answer does exactly what you are asking for.

**Comment by rolfen** [comment]
> @rolfen My arrogant and useless answer does exactly what you are asking for.

I wish it did!

BSSIDs identifiers for access points or wireless routers. As far as I know clients are not assigned BSSIDs ever. Clients are identified by MAC addresses. I was unable to map any of the listed BSSIDs to any of the clients that should be showing up in this list, despite my best efforts.

I'm not sure what is happening here but it looks like a list of access points.

**Comment by evilsocket** [comment]
There must be a problem in communication here, probably due by the fact that i use the acronym BSSID to indicate both the AP (specifically its MAC address) and the MAC address of the client stations. 

So, are you trying to list all clients for a given AP? If that is the case and I understood correctly, wifi.recon BSSID (of the AP of course) should do it. If you don't see a list of clients, maybe disable channel hopping and fix the channel to the one of the AP in order to detect the clients? 

You reported this view:

```
6a:16:1b:64:b0:b4 clients:

┌─────────┬───────────────────┬────┬───────┬────────┬──────────┐
│ RSSI ▴  │       BSSID       │ Ch │ Sent  │ Recvd  │   Seen   │
├─────────┼───────────────────┼────┼───────┼────────┼──────────┤
│ -50 dBm │ c8:31:35:de:fa:3d │ 9  │ 78 kB │ 8.0 kB │ 22:22:47 │
│ -59 dBm │ 2e:21:02:13:a5:1a │ 9  │ 72 kB │ 103 kB │ 22:22:29 │
└─────────┴───────────────────┴────┴───────┴────────┴──────────┘
```

Where 6a:16:1b:64:b0:b4 is the AP (the BSSID you filtered for) and the two entries in the table are the two connected clients ... isn't this what you are asking for?

I'm kind of lost here ....

**Comment by rolfen** [comment]
I'm also a bit lost, maybe I was just confused and maybe it is indeed what I was looking for. Sorry for being rude. Thanks for listing the procedure.
