### ISSUE TITLE
Rpi0 https-ui crash

### ISSUE THREAD

**Issue by Decapitater** [bettercap/bettercap#904]
Bettercap exits after panicing due to PEM data.
### Environment

Please provide:

*version=v2.31.1
* kali arm64.
* sudo bettercap
*https-ui on.
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
loading TLS certificate from /root/.bettercap-https.cert.pem
loading TLS certificate from /root/.bettercap-https.cert.pem
api server starting on https://0.0.0.0:8083
panic:tls:failed to find any PEM data in certification input 
### Steps to Reproduce
1. connect to any device via ssh [can use create_ap]
2.  type "sudo bettercap"
3. type "https-ui on"
4. tada bettercap exits itself with the above provided output
**Expected behavior:** bettercap will start a service and we would be able to see the web ui on the connect device via the ip
**Actual behavior:** Bettercap just Exited 
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by Decapitater** [comment]
@evilsocket  help ?

**Comment by evilsocket** [comment]
it looks like those pem files are corrupted, possibly because the rpi0 has been turned off while it was generating them the first time. 
Try to delete those two files and launch bettercap again, then wait for it to correctly generate them. On a Rpi0 it can take several seconds, possibly a couple of minutes, just the first time. Let it be, and it will work.

**Comment by Decapitater** [comment]
well i have removed bettercap and then again i downloaded it so what's next ?

**Comment by Decapitater** [comment]
thanks for such fast response man 
now its working all thanks to you.
do you have a telegram ? may chit-chat on some topics of interests
